name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0x

    - name: Install dependencies
      run: npm install --force

    - name: Lint with ESLint
      run: npm run lint

    - name: Format with Prettier
      run: npm run prettier

    - name: Test
      run: npm test

    - name: Build
      run: npm run build