name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install --force

    - name: Build
      run: npm run build --if-present

    - name: Run tests
      run: npm test



    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.empreendedorfina1.hospedagemdesites.ws
        user: empreendedorfina1
        password: R3&zPb9ZTu1>Z@
        localDir: "dist"